# -*- coding: utf-8 -*-
"""lenierR2score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JnjPVe-CEulVK1iGgslSldFh4nXqPND
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

df = pd.read_csv("/content/headbrain.csv")
df.head()

X = df["Head Size(cm^3)"].values
Y = df["Brain Weight(grams)"].values
#print(X)
#print(Y)

#model initialization
reg = LinearRegression()

n =len(X)

X =X.reshape(n,1)
#model fitting
reg = reg.fit(X,Y)

#Y prediction
Y_pred= reg.predict(X)

#print(Y_pred)

#model evaluation
rmse = np.sqrt(mean_squared_error(Y,Y_pred))
r2 = r2_score(Y,Y_pred)

print(rmse)
print(r2)